name: recurrent-analytics
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - seaborn
  - xarray
  - cfgrib
  - eccodes
  - netcdf4
  - h5netcdf
  # Optional, nice to have:
  # - cartopy           # maps/projections (larger)
  # - cftime            # robust time decoding
